security:
  basic:
    enabled: true

management:
  security:
    enabled: false
    clearwater: true

logging:
  level:
    io:
      pivotal: DEBUG

spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct
